name: VNVTStore CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  backend:
    name: Backend (Build & Test)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./VNVTStore.Backend

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Install SonarScanner
      run: |
        dotnet tool install --global dotnet-sonarscanner

    - name: Restore Dependencies
      run: |
        dotnet restore src/VNVTStore.API/VNVTStore.API.csproj
        dotnet restore src/VNVTStore.Tests/VNVTStore.Tests.csproj

    - name: Begin SonarCloud Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: ${{ secrets.SONAR_TOKEN != '' }}
      run: |
        dotnet sonarscanner begin /k:"${{ secrets.SONAR_PROJECT_KEY }}" /o:"${{ secrets.SONAR_ORG }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

    - name: Build API
      run: dotnet build src/VNVTStore.API/VNVTStore.API.csproj --no-restore --configuration Release

    - name: Run Tests
      # Added coverage collection for Sonar
      run: dotnet test src/VNVTStore.Tests/VNVTStore.Tests.csproj --configuration Release --verbosity normal --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

    - name: End SonarCloud Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: ${{ secrets.SONAR_TOKEN != '' }}
      run: |
        dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

  frontend:
    name: Frontend (Build & Test)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./VNVTStore.Frontend

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ./VNVTStore.Frontend/package-lock.json

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test -- run

    - name: Build
      run: npm run build
