name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Debug Secrets
        run: |
            echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"
            echo "Docker Password: ${{ secrets.DOCKER_PASSWORD }}" | sha256sum
          
      - name: Debug Secrets
        run: |
          echo "Docker Username: tienvo3008@gmail.com"
          echo "Docker Password: 0329922209Tien@"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tienvo3008@gmail.com
          password: 0329922209Tien@

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./vnvt-back-end
          push: true
          tags: tienvo3008/vnvtstoreapp:latest
